---
http_interactions:
- request:
    method: post
    uri: http://10.0.6.2:4243/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Cmd":["/bin/sh","-c","while true; do echo hello world; sleep 1;
        done"],"Image":"base"}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: !binary |-
        Q3JlYXRlZA==
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        dGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOA==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        U2F0LCAzMSBBdWcgMjAxMyAxMDoxMTozMyBHTVQ=
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        eyJJZCI6Ijg1ODlhOTg0NjUzMiJ9
    http_version: 
  recorded_at: Sat, 31 Aug 2013 10:11:37 GMT
recorded_with: VCR 2.5.0
